//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mimir.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ni88\\Desktop\\")]
        public string optionsT1_source {
            get {
                return ((string)(this["optionsT1_source"]));
            }
            set {
                this["optionsT1_source"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\ni88\\Desktop\\custom\\")]
        public string optionsT1_destination {
            get {
                return ((string)(this["optionsT1_destination"]));
            }
            set {
                this["optionsT1_destination"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature1_check {
            get {
                return ((bool)(this["optionsT1_Feature1_check"]));
            }
            set {
                this["optionsT1_Feature1_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature2_check {
            get {
                return ((bool)(this["optionsT1_Feature2_check"]));
            }
            set {
                this["optionsT1_Feature2_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature3_check {
            get {
                return ((bool)(this["optionsT1_Feature3_check"]));
            }
            set {
                this["optionsT1_Feature3_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature4_check {
            get {
                return ((bool)(this["optionsT1_Feature4_check"]));
            }
            set {
                this["optionsT1_Feature4_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature5_check {
            get {
                return ((bool)(this["optionsT1_Feature5_check"]));
            }
            set {
                this["optionsT1_Feature5_check"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool optionsT1_Feature6_check {
            get {
                return ((bool)(this["optionsT1_Feature6_check"]));
            }
            set {
                this["optionsT1_Feature6_check"] = value;
            }
        }
    }
}
